### ISSUE TITLE
Difference between master and vXX

### ISSUE THREAD

**Issue by der-On** [geddy/geddy#672]
I don't fully understand the vXX branches versus the master branch.
Isn't the master supposed to be the latest and the vXX the stable/LTE branches? 
Currently it seems like v13 is the latest while master is something in between current and old. :/ I was always committing to the master branch. 

I'm curious where to contribute to now and what master is ment for in geddy?
Can we just merge v13 into master?

**Comment by der-On** [comment]
Could you please clarify? Thanks in advice.

**Comment by mde** [comment]
This has caused continuous confusion for people. Everyone always wants to assume that everything is happening in master. In theory we're always merging the release branches back to master so we get bugfixes, and new development is happening in master. In practice, nobody understands what's happening. :)

I have no problem moving to a "release from master" strategy. I just want to make sure we're never in a position where we can't push out a release because there's a bunch of new development sitting in the branch that we want to release from. There are some things we could do in the case where new development work has landed in master (e.g., branching off the last release tag, and adding the fix there). These might be a little confusing, but it would only affect the person trying to land the bugfix.

**Comment by der-On** [comment]
So I could basically merge v13 into master?

And we just have to keep the release branches clean of new (blocking) features.

You should add this information to the [wiki](https://github.com/geddy/geddy/wiki/Contributing-to-Geddy).

**Comment by mde** [comment]
Yes, you should always merge v13 into master.

**Comment by der-On** [comment]
I've just tried to clarify it in the wiki: https://github.com/geddy/geddy/wiki/Contributing-to-Geddy#master-feature-and-release-branches

Please have a look and edit to your pleasure.
